name: count the number of asdf plugins
on: workflow_dispatch
jobs:
  count-asdf-plugins:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - uses: asdf-vm/actions/setup@6a442392015fbbdd8b48696d41e0051b2698b2e4 # v2.2.0
      - run: asdf plugin list all | wc -l
