---
name: test-pinact
on: workflow_call
jobs:
  integration-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@v0.5.0
    with:
      aqua_version: v2.3.4
    permissions:
      pull-requests: write
      contents: read
