---
name: wc-test
on: workflow_call
jobs:
  foo:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 5
    steps:
      - run: echo "$GITHUB_WORKFLOW_SHA"
      - run: echo "$GITHUB_WORKFLOW_REF"
